# 工作流名称
name: CI

# 触发事件  （ workflow_dispatch： 手动点击  ）
on: workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        run: ${{ format('Hello++{0}++{1}++{2}', 'Mona', 'the', 'Octocat') }}
          
