# 工作流名称
name: CI

# 触发事件  （ workflow_dispatch： 手动点击  ）
on: workflow_dispatch

## 多个任务， 默认并行
jobs:
  # 任务名称 （ 自定义 ）
  build_hello_name:
    # 指定任务运行在哪个操作系统上
    runs-on: ubuntu-latest

    # 执行流程 （多个步骤）
    steps:
      # 调用工具， 模拟 git clone && cd $project_dir
      - name: 检出代码V4
        uses: actions/checkout@v4
        # ok
      - name: ok
        run: okay
          
