# 工作流名称
name: CI

# 触发事件  （ workflow_dispatch： 手动点击  ）
on: workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: |
          chmod +x ./hello.sh
          ./hello.sh
          
